//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_ParanaSeguros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos_Caja
    {
        public int Id_Movimiento_Caja { get; set; }
        public Nullable<int> Id_Caja { get; set; }
        public Nullable<System.DateTime> Fecha_Movimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Tipo_Movimiento { get; set; }
    
        public virtual Cajas Cajas { get; set; }
    }
}
